### ISSUE TITLE
GITHUB使用问题

### ISSUE THREAD

**Issue by smalkang** [ypwhs/smartCar#2]
![image](https://user-images.githubusercontent.com/39072137/57178516-eb6ca000-6ea3-11e9-87ff-976456c4ab6f.png)
你好，为什么我这里一直有显示

**Comment by ypwhs** [comment]
因为你提交过一个空格的 pr，https://github.com/ypwhs/smartCar/pull/1

**Comment by smalkang** [comment]
所以说我怎么才能在我这边不显示
